use std::{env, fs, path::Path};

fn main() {
    generate_glyphs();
    tauri_build::build()
}

/// The Windows taskbar thumbnail toolbar draws the SAME artwork as the in-app
/// transport row, lifted out of `index.html` at build time rather than copied
/// into Rust — so a redesign of the UI icons can't silently leave the taskbar
/// buttons showing the old glyphs. A missing id fails the build loudly.
fn generate_glyphs() {
    const HTML: &str = "../index.html";
    const IDS: &[&str] = &[
        "thumbDown",
        "replay",
        "play-icon",
        "pause-icon",
        "skip",
        "thumbUp",
    ];

    println!("cargo:rerun-if-changed={HTML}");
    let html = fs::read_to_string(HTML).expect("build.rs: cannot read app/index.html");

    let mut out = String::from("// @generated by build.rs from app/index.html — do not edit.\n");
    out.push_str("/// Inner markup of each transport <svg>, keyed by its element id.\n");
    out.push_str("pub const GLYPHS: &[(&str, &str)] = &[\n");
    for id in IDS {
        out.push_str(&format!(
            "    ({id:?}, r##\"{}\"##),\n",
            svg_inner(&html, id)
        ));
    }
    out.push_str("];\n");

    let dst = Path::new(&env::var("OUT_DIR").unwrap()).join("glyphs.rs");
    fs::write(dst, out).unwrap();
}

/// Contents of the `<svg>` element carrying (or wrapping) `id` — the `<path>`
/// children only, so the caller can supply its own sizing and paint attributes.
fn svg_inner(html: &str, id: &str) -> String {
    let key = format!("id=\"{id}\"");
    let at = html.find(&key).unwrap_or_else(|| {
        panic!("index.html has no element with {key}, which the taskbar thumbnail toolbar needs")
    });

    // The id sits either on the <svg> itself (play-icon / pause-icon) or on the
    // wrapping <button>. If the nearest preceding "<svg" has no ">" between it
    // and the id, the id is inside that open tag; otherwise take the next one.
    let open = match html[..at].rfind("<svg") {
        Some(s) if !html[s..at].contains('>') => s,
        _ => at + html[at..].find("<svg").expect("no <svg> follows the id"),
    };
    let body = open + html[open..].find('>').expect("unterminated <svg> tag") + 1;
    let end = body + html[body..].find("</svg>").expect("unclosed <svg> element");
    html[body..end].trim().to_string()
}
